#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

#shots:
  #outlane_left:
  #switch: s_left_outlane

  #inlane_left:
  #switch: s_left_inlane

#variable_player:
  #outlane_left_hit:
    #score: 100
  #inlane_left_hit:
    #score: 200