#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

config:
  - config_switches.yaml
  - config_ball_devices.yaml
  - config_coils.yaml

hardware:
    platform: fast


fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      

#Here is where you will add any additional switch / driver boards. Order is counted by 1 beginning connected to the neuron and then each one added would be order: 2, order: 3. The name of the board can be anything and will be used when defining coils or switches.

      3208:
        model: FP-I/O-3208
        order: 1


modes:
  - attract
  #- base


  
#displays:
  #window:
    #width: 800
    #height: 600

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    #enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    #enable_events: machine_reset_phase_3

autofire_coils:
  left_sling:
    coil: c_sling_left
    switch: s_slingshot_left 

  right_sling:
    coil: c_sling_right
    switch: s_slingshot_right