#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

hardware:
    platform: fast


fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      

#Here is where you will add any additional switch / driver boards. Order is counted by 1 beginning connected to the neuron and then each one added would be order: 2, order: 3. The name of the board can be anything and will be used when defining coils or switches.

      3208:
        model: FP-I/O-3208
        order: 1


#modes:
 # - attract
  #- base
  
#displays:
  #window:
    #width: 800
    #height: 600

switches:

  s_plunger:
    number: 3208-7

  s_trough_ball_jam:
    number: 3208-6
    type: 'NC'

  s_trough_ball_1:
    number: 3208-0
    type: 'NC'

  s_trough_ball_2:
    number: 3208-1

  s_trough_ball_3:
    number: 3208-2

  s_trough_ball_4:
    number: 3208-3

  s_trough_ball_5:
    number: 3208-4

  s_trough_ball_6:
    number: 3208-5

  s_left_flipper:
    number: 3208-27
    tags: left_flipper
  s_right_flipper:
    number: 3208-24
    tags: right_flipper

  s_slingshot_left:
    number: 3208-15
    tags: slingshot_left
  s_slingshot_right:
    number: 3208-9
    tags: slingshot_right

#Other Buttons

  s_start:
    number: 3208-26
    tags: start
    #type: NC

  s_launch:
    number: 3208-25
    tags: launch
  
#Lane Switches
  s_left_outlane:
    number: 3208-13
    tags: outlane_left
  s_left_inlane:
    number: 3208-14
    tags: inlane_left
  s_right_inlane:
    number: 3208-10
    tags: inlane_right
  s_right_outlane:
    number: 3208-11
    tags: outlane_right
  s_flipper_left_eos:
    number: 3208-12
    tags: flipper_left_eos
    type: NC
  s_flipper_right_eos:
    number: 3208-8
    tags: flipper_right_eos
    type: NC


coils:
  c_flipper_left_main:
    number: 3208-3
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 3208-2
    allow_enable: true
  c_flipper_right_main:
    number: 3208-5
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 3208-4
    allow_enable: true

playfields:
  playfield:
    tags: default
    default_source_device: None  # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3